# Generated by Django 5.2.1 on 2025-05-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')), 
                #serialize = pegar dados dentro do banco e converter eles para JSON para que eles possam ser compartilhados externamentes e vice versa
                #para nao ser compartlhado, é por padrao false, mas para que possam ser compartilhados, vamos colocar true
                #em seguida fazer os migrations e migrate la para aplicar as alterações
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.CharField(max_length=100)),
            ],
        ),
    ]
