# Generated by Django 5.2.1 on 2025-06-06 11:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_bairro_usuario_cep_usuario_localidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cartao', models.CharField(max_length=16)),
                ('validade', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
                ('data_compra', models.DateTimeField(default=datetime.datetime.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
